In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [8]:
df=pd.read_csv('/home/spydr/Downloads/Corpus/Datasets/homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  680000
4  4000       5.0   18  725000
5  4100       6.0   16  690000

In [10]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [12]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  680000
4  4000       5.0   18  725000
5  4100       6.0   16  690000

In [16]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [17]:
reg.coef_

array([   181.84101976, -42790.21803182,  -3127.0353255 ])

In [18]:
reg.intercept_

254646.27981267218

In [20]:
reg.predict([[3000,3,40]])

/home/spydr/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([546717.27196601])

In [47]:
reg.predict([[2600,3,15.7295999]])

/home/spydr/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([549875.26254016])