In [61]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split,GridSearchCV,cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [2]:
iris = load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [5]:
df['target'] = iris.target

In [6]:
X = df.drop('target',axis=1)
y=df.target

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=45)

In [29]:
model=RandomForestClassifier()

In [30]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [37]:
model.score(X_test,y_test)

0.9333333333333333

In [32]:
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']
}

In [33]:
grid_search = GridSearchCV(model,param_grid,cv=5,scoring='accuracy')

In [34]:
grid_search.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [None, 10, 20],
                         'max_features': ['sqrt', 'log2'],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [50, 100, 200]},
             scoring='accuracy')

In [64]:
best_params = grid_search.best_params_

# Train Random Forest Classifier with the best parameters
best_rfc = RandomForestClassifier(**best_params)
best_rfc.fit(X_train, y_train)

RandomForestClassifier(min_samples_leaf=4, n_estimators=50)

In [36]:
best_rfc.score(X_test,y_test)

0.9333333333333333

In [40]:
model_2 = DecisionTreeClassifier()

In [41]:
model_3 = SVC()

In [56]:
model_4 = LogisticRegression(max_iter=1000)

In [51]:
cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=3)

array([0.98, 0.92, 0.96])

In [54]:
cross_val_score(model_3,iris.data,iris.target,cv=3)

array([0.96, 0.98, 0.94])

In [57]:
cross_val_score(model_4,iris.data,iris.target,cv=3)

array([0.98, 0.96, 0.98])

In [59]:
cross_val_score(model,X,y,cv=3)

array([0.98, 0.94, 0.98])

In [67]:
score = cross_val_score(best_rfc,iris.data,iris.target,cv=15)
np.average(score)

0.9533333333333334

In [80]:
score_1 = cross_val_score(RandomForestClassifier(n_estimators = 40),X,y,cv=10)
np.average(score_1)

0.96